/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exampleContracts from "./example-contracts";
export type { exampleContracts };
export type { FundMe } from "./FundMe";
